/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  REGION: "ap-southeast-1",
  USER_POOL_ID: "ap-southeast-1_LNhz2fwfg",
  USER_POOL_APP_CLIENT_ID: "3r4t67lkqeak704n9jarm99age",
};

export default awsmobile;
